### ISSUE TITLE
Add in_profile_velocity and out_profile_velocity to the resultlist

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-core#120]
**Summary**

Add in_profile_velocity and out_profile_velocity to the resultlist

**Detailed Description**

The results give a velocity-value. Its exact meaning is not clear to me.

I would prefer if a distinct value for a in_profile_velocity and a out_profile_velocity could be provided.

**Comment by axtimhaus** [comment]
`in_profile.velocity` and `out_profile.velocity` are already present. The `RollPass.velocity` hook means what is commonly called "the rolling velocity". This is something like a mean material velocity in the roll pass. By default it is directly coupled with the roll surface velocity and the neutral line. `RollPass.OutProfile.velocity` will fallback to `RollPass.velocity` by default.

There is a plugin `pyroll-local-velocity` (currently not public) calculating the in and out velocities from volume constance, but this needs information about local material flow. So this will be published with the pillar model once the API is fixed (currently under heavy refactoring).

(@ChRen95 FYI)
