### ISSUE TITLE
Provide a helper-function for 3-roll process to calculate gap-value from inner circle 

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-core#121]
**Summary**

For 3-roll processes the actual rollposition is specified by providing a innerdiameter rather than the gap-value.

PyRolL should provide a method to calculate the gap-value from a given innerdiameter
or
it shoulb be spossible to simply provide the innerdiameter instead of the gap-value.

**Detailed Description**

Possible solution:
based on https://stackoverflow.com/questions/39840030/distance-between-point-and-a-line-from-two-points

P1 = np.array([0,0])
P2 = np.array([1, np.tan(np.radians(30))]) * convert_SI['length']

px = np.array([Stand.roll.contour_points[-1][0] for Stand in PassSequence])
py = np.array([Stand.roll.contour_points[-1][1] for Stand in PassSequence])

maxIndex = np.array([list(Stand.roll.contour_points[:,0]).index(0.0) for Stand in PassSequence])

pymax = [Stand.roll.contour_points[maxIndex[n],1] for n, Stand in enumerate(PassSequence)]

offset = InnerRadius - pymax

P3 = np.vstack((px, py + offset)).T

gap_from_Di = 2 * np.abs(np.cross(P2-P1, P1-P3)) / np.linalg.norm(P2-P1)

**Comment by ChRen95** [comment]
What is the classic name for this variable?
Inner circle diameter?

**Comment by GRPlan** [comment]
https://www.researchgate.net/publication/318790213_An_approximate_model_to_predict_the_surface_profile_of_material_sections_in_a_3-roll_rolling_process
uses the term inscribed circle diameter
which I find quite suitable

Kocks uses the term Kaliberanstellung (DSA) in BAMICON Mill Manager

**Comment by ChRen95** [comment]
Okay, will be published with next minor change then.
