### ISSUE TITLE
Roadmap for development of PyRolL

### ISSUE THREAD

**Issue by axtimhaus** [pyroll-project/pyroll-core#13]
Discussion regarding the [roadmap](../blob/main/ROADMAP.md) can be placed here.

**Comment by ChRen95** [comment]
I would bring forward the rolling with 3 rolls. As it is important for symmetrical break down grooves.
So in my opinion, 1.1 should first support 3 rolls, then continue further.

**Comment by axtimhaus** [comment]
see changes in #14

**Comment by axtimhaus** [comment]
Our first idea was to implement spacial resolution in rolling direction (x-direction) by use of the strip element / disk element concept and mirror the unit concept within this.

This would have the following benefits:

* possibility of using the same hook system for including models within the strip elements
* high flexibility in model inclusion

However the are drawbacks:

* computation speed, main concern since hook resolution is slow
* need to transfer all current single-step models to disk resolution
* hard to use single-step models and x-resolved models together

Another possibility would be to just include a hook `RollPass.intermediate_profiles` that yields a list of intermediate profile instances (e.g. `RollPass.IntemediateProfile(RollPass.Profile)` like already done with `RollPass.InProfile` and `RollPass.OutProfile`).

* save 50% of profile-like instances
* fewer plugin host classes
* basic single-step models can be used alongside
* keep possibility to plot intermediate profiles easily and use hooks of `Profile` base class

Needed base implementations:

* for common profile properties like strain and temperature as linear interpolations between in and out profiles, if no better option available (e.g. for use of local flow stress)
* hook on all units for count of intermediate profiles as well as the `intermediate_profiles` hook itself
* for common unit properties like roll force and roll torque as mean resp. integral values of the intermediate profiles

**Comment by axtimhaus** [comment]
In the course of the development of the system for spacial resolution, the current plugin system starts to show its nasty sides.

- Necessity to define hooks at each derived class again with the new set of arguments 
    - huge code redundancy
    - becomes even worse when new units are introduced (3-roll passes, asymmetric passes)
    - error prone
- Friction between plugins, when one plugin defines a hook and another one with the same name 
    - throws an error if hook already defined in a plugin manager
    - but prevents from ambiguous hooks
    - problematic when hooks of base classes in core are redefined on derived classes due to need for access to other objects (f.e. to the unit instance from a hook on profiles)

I plead to shift the spacial resolution to version 2.0, because with the current system it becomes a mess.
The plugin system must become drastically leaner and easier to maintain in version 2.0, which might not be possible without breaking changes.

My thoughts on how to accomplish this:

- Host plugin managers only on base classes representing basic concepts (`Profile`, `Unit`, `Roll` for now)
    - derived classes only call on plugin managers of their base
    - lowers the count of `plugin_manager.register()` and `plugin_manager.add_hookspecs()` calls in plugins, thus less clatter code
    - `hookimpl` decorators may be preserved, but changed to check wrappers returning `None` if not instance of required child class
- make all hooks using the same signature with one `self` argument similar to classic methods
    - access to connected instances by attributes, references to them are currently hold in `hook_args` anyway, just shift them out as distinct attributes
    - encourage the user to use explicit `hasattr()` calls to check if f.e. a profile is currently connected to a roll pass
    - this makes hook functions more general and reusable, especially if number of distinct unit grows

This system would significantly decrease the number plugin manger instances to maintain, especially with regard to future where number of classes will increase. Although, the number of `if` conditions checking the availability of some data will increase in hook function code. But also the hierarchical scanning of plugin managers for hookimpls is dropped.
