### ISSUE TITLE
Improve internal naming schemes to work with autocompletion in jupyter notebooks

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-core#142]
**Summary**

Some internal names like e.g. ThreeRollPass 'Pass4' are incompatible with autocompletion in jupyter notebooks.
They are not displayed in the autocompletion list.

This is at times quite comfusing when looking for specific results.

It would be better if internal names are created in a way so that they support autocompletion.

![image](https://github.com/pyroll-project/pyroll-core/assets/144011375/7a93239a-56f0-4340-a9cb-9805fd5a9f40)

**Comment by axtimhaus** [comment]
Do you refer to the string representation of units?
Where does this affect autocompletion?

**Comment by GRPlan** [comment]
Yes, I refer to the string representation of units.
I think autocompletion can't deal e.g. with . and space.
Respective units do not appear in the autocompletion list which is confusing to the user.

![image](https://github.com/pyroll-project/pyroll-core/assets/144011375/b9ff8a1c-6eb6-4769-a2df-cb2dc146ca22)

In the list above I would expect the ThreeRollPass units to be present in the autocompletion list.

**Comment by axtimhaus** [comment]
What is this `Rollpass` object in your case? I do not know of any where the units were accessible by label. But this may be an idea to implement an indexer in `PassSequence` which allows to get units by label like `sequence["Oval III"]` if `sequence` is a `PassSequence` and there is a unit with `label="Oval III"` in.
