### ISSUE TITLE
Make certain that strain_rate is always displayed in PassSequence Summary

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-core#144]
**Summary**

In analysis of forming processes temperature, strain and strain_rate are the fundamental state variables.

The PassSequence summary should alsways provide these values.

Strain_rate values seem to be available in the reults database but is not added to the Summary when a flowcurve calculation method with no strain_rate dependance is used.

**Comment by ChRen95** [comment]
@GRPlan can we close this issue?
