### ISSUE TITLE
Arbeitenden Durchmesser richtig definieren

### ISSUE THREAD

**Issue by msch67** [pyroll-project/pyroll-core#15]
arbeitender Durchmesser über $D_W - h_{1m}^"$ definieren !!!
Sonst ist der Walzendurchmesser für diverse Rechnungen zu groß.
Die obige Darstellung sichert, dass der reale Walzstich mit dem äquivalenten zusammenpasst.

**Comment by ChRen95** [comment]
Laut 
[Dong2008.pdf](https://github.com/pyroll-project/pyroll-core/files/9763548/Dong2008.pdf) liegt der Fehler der von uns verwendeten Method nach Wusatowski bei etwa 1%.
