### ISSUE TITLE
Bug in Generic_Elongation_Solvers

### ISSUE THREAD

**Issue by ChRen95** [pyroll-project/pyroll-core#159]
**Summary**

When you use a `ConstrictedBoxGroove` using the follwing definition: 

` groove=ConstrictedBoxGroove(
                        r1=1.805e-3,
                        r2=6.859e-3,
                        r4=31.5875e-3,
                        depth=4.9565e-3,
                        indent=0.361e-3,
                        usable_width=24.2e-3,
                        ground_width=17.5e-3,
                    ),
                    nominal_radius=160e-3,
                    rotational_frequency=1,
                ),
                gap=2e-3,`

the solver yields a negative usable_width resulting in an Error of the `mandatory_positive_or_zero` list.

**PyRolL Version and Platform**

pyroll-core 2.1.3

**Comment by axtimhaus** [comment]
Can you provide a drawing for this? I tried to draw the groove with your values in CAD and it seems to be geometrically impossible to me. So I suspect no bug, but invalid input...

**Comment by ChRen95** [comment]
Seem's that I used the wrong dimensions. No Bug!
