### ISSUE TITLE
Revise Definition of Transport Length

### ISSUE THREAD

**Issue by axtimhaus** [pyroll-project/pyroll-core#169]
Second thought on #168: 

Currently transport have a fixed length in conti lines. But the actual length of the transport in reality is dependent on the contact length, since the position of the rolling stand is fixed.

Possible implications:

- Add a coordinate positioning of roll passes by defining a coordinate in `x` as new hook.
- Add a new hookimpl to transports to compute their length in terms of roll pass coordinates and entry resp. exit points of the workpiece their. *Must work iterating in the pass sequence because of access to next unit.* 
- Must respect roll shadow (spray zones near passes) if present, see #167 and #168.
- Current behavior with given length of transport should remain the same.

**Comment by ChRen95** [comment]
Would the first suggestion: 
"Add a coordinate positioning of roll passes by defining a coordinate in x as new hook."
Not also be able by overriding the `entry_point` hook?

**Comment by axtimhaus** [comment]
I would fix the rolling stand position at the high point, so the internal `x=0` of the rolling stand has a defined position.
