### ISSUE TITLE
Improve Contur representation by adding more points

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-core#170]
At the moment RyRoll uses a minimalistic approach to represent result conturs. Straight segments just have a start- and endpoint, no mater how long they actually are.

![Kontur_0a](https://github.com/pyroll-project/pyroll-core/assets/144011375/2a9f2075-664d-4879-a194-bf4e445c22ef)

For comparison with conturs from measurements or FEM calculations user might consider the use of polar coordinates.
For this approach it is beneficial when more points are present on the contur.

![Kontur_1a](https://github.com/pyroll-project/pyroll-core/assets/144011375/fe73c6d4-36b4-4222-8bb1-a4d5b178456b)

My current appraoch to improve the contur-representation uses length and segmentize from shapely package.

        perimeter = length(out_profile)
        out_profile = out_profile.segmentize(perimeter / divions)

divisions is a parameter to control the level of refinement. For me divisions = 50 yields good results in medium to small size KOCKS processes.

Check whether it is possible to make this a PyRoll standard behavior.

**Comment by axtimhaus** [comment]
We may add a config parameter for the divisions, so zero means than no further refinement, and positive values refine the overall profile. But I would stick to no refinement as default. You could then refine all profiles with one line before solving like this:

```python
from pyroll.core import Config

Config.PROFILE_CONTOUR_REFINEMENT = 50
```
