### ISSUE TITLE
cross section filling ratio | filling ratio

### ISSUE THREAD

**Issue by KoosVanPutten** [pyroll-project/pyroll-core#190]
Can you please explain the difference between "filling ratio" and "cross section filling ratio" ?

Furthermore documentation or reference - containing a sketch and the subsequent formula - regarding the calculation of these two values would be helpfull.

**Comment by ChRen95** [comment]
Hi Koos, 
So the filling ratio "classically" is calculate as follows: 


$$ i = \frac{w_u}{w_1} $$
with $w_1$ being the final width of the exiting profile and $w_u$ being the usable width of the groove. 
Another way of calculating the filling ratio is using the corresponding cross-sections.
I attached two pictures that should help to understand the concept.

[circular_oval_groove.pdf](https://github.com/pyroll-project/pyroll-core/files/14663470/circular_oval_groove.pdf)
[circular_oval_profile.pdf](https://github.com/pyroll-project/pyroll-core/files/14663467/circular_oval_profile.pdf)

**Comment by KoosVanPutten** [comment]
Thank you.
I assume that i_A is the cross section filling ratio.

The two pictures, can they be found somewhere in a github directory?
I would like to see this sketch for box-groove.
