### ISSUE TITLE
Rotational Frequency and Surface Velocity of Rolls Wrong When Pass Velocity Given

### ISSUE THREAD

**Issue by axtimhaus** [pyroll-project/pyroll-core#209]
- Two Pi in `Roll.surface_velocity` Hook missing
- Connection between `Roll.surface_velocity` and different radii of roll unclear (working or max radius?)

**Comment by ChRen95** [comment]
surface_velocity is defined as: 

`self.rotational_frequency * self.nominal_radius * 2 * np.pi`

Where do you see a missing 2 Pi?

Second question I don't see different radii. Is it because we use `working_radius` for the neutral angle?

**Comment by axtimhaus** [comment]
The other way round 

```
@Roll.rotational_frequency
def rotational_frequency(self: Roll):
    return self.surface_velocity / self.nominal_radius
```

The question is the connection to `RollPass.velocity`, which is commonly approximated using the working diameter, but currently implemented using `Roll.surface_velocity`

**Comment by ChRen95** [comment]
Now I see. I would suggest to use working radius. 
That would increase the velocities, maybe @msch67 @mscImf has another idea but I always thought from his lectures that the working radius is connected to the neutral point.

**Comment by ChRen95** [comment]
I recently encountered a problem witch was brought up by ESF. They set the machine speed using the working radius. Therefore we should use the working radius as well.
