### ISSUE TITLE
ThreeRollPasses are rotated wrong/ unintuitively

### ISSUE THREAD

**Issue by RichardPfr** [pyroll-project/pyroll-core#221]
**Summary**

When no rotation or orientation is set for a ThreeRollPass they are displayed/ processed with the horizontal line at the top (see picture). This is also the orientation one gets when setting the orientation to "horizental", "h" or "y" or the rotation to 0°. 
<img src="https://github.com/pyroll-project/pyroll-core/assets/114106640/2684f4b9-b167-4c9f-ab93-ddbdde824fc1" width="350" height="300">

**PyRolL Version and Platform**

PyRolL 2.1.6; Windows

**Expected Behavior**

The expected behaviour would probably have it rather be orientated by 180° as the standard orientation. Currently this can be achieved by setting orientation to "antiy" or "y". Then we get: 
<img src="https://github.com/pyroll-project/pyroll-core/assets/114106640/b8e98ccf-1cfa-4ff4-adc4-2f093e201226" width="350" height="300">

Shouldnt this be the standard setting? So when no orientation or rotations are set (or when they are set to "horizental", "h", "y" or 0°)?
Out [documentation](https://pyroll.readthedocs.io/en/latest/core/units/roll_pass/three_roll_pass.html) also shows this as the default orientation.

**Comment by RichardPfr** [comment]
@axtimhaus is this even wanted or are there other reasons i dont see why its oriented this way? 

If we want to have it rotated the other way is it sufficient to cahnge and add rotations to the contour_lines property, or are there other changes necessary to have it calculate correctly?

**Comment by axtimhaus** [comment]
Why this would be more *expected* then the other way?
I the current view we have the height direction in vertical and the width somewhat sideways in the upper part of the roll pass. This seems quite natural to me, although the other way would be not much less.

**Comment by ChRen95** [comment]
@RichardPfr do you have an answer?

**Comment by RichardPfr** [comment]
After talking back to G. Rothenbucher and M. Molter the behaviour should be changed as I described it. Kocks themselves describe them as seen in Pic 1 as 'AntiY' and as seen in Pic 2 as 'Y', because it is about the orientation of the rolls not the roll gaps. 

At the end both is pretty much the same, but we should probably still rather adapt to the syntax as it is used in the industry.

**Comment by ChRen95** [comment]
So standard orientation is Y. That would mean we should change Y and Anti Y?

**Comment by RichardPfr** [comment]
Made some updates in #222:

The ThreeRollPasses should now be inherently orientated as shown above. 
I didnt want to just change the use of Y and AntiY in the following though:

https://github.com/pyroll-project/pyroll-core/blob/e108897ab1bc7335c292523921ffc4828af64087/pyroll/core/roll_pass/roll_pass.py#L247-L256

Doing so would have meant that orientation Y would be associated with 180° of rotation, even though it should be the standard (so 0°). Also it would require the user to always define orientation="y" on the first pass or else one would again get the AntiY orientation in each first pass. (calculation wise this makes no difference but still)


The changes made may also require updates to some other plugins, as was already the case in pyroll-project/pyroll-lendl-equivalent-method#5
