### ISSUE TITLE
Add Default Front and Back Tensions

### ISSUE THREAD

**Issue by ChRen95** [pyroll-project/pyroll-core#242]
**Summary**

Since we want to provide algorithms for the calculation of tensions in between roll passes, default values for the `front_tension` and `back_tension` are needed. I would suggest we provide them as 0 in the hookimpls. 
This would add the concept of having a tension free process to the core. 
Approving @axtimhaus @RichardPfr ?

**Comment by axtimhaus** [comment]
Seems reasonable

**Comment by RichardPfr** [comment]
Yes seems good
