### ISSUE TITLE
Provide number of rolls as numerical value

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-core#254]
**Summary**

When performing customized calculations it can be beneficial to have access to the number of rolls as a numerical value.

E.g. for force or torque calculatations I use the following line to provide roll_number (probably better number_of_rolls...)

df['roll_number'] = df.apply(lambda row: 3 if row.roll_type.startswith('Three') else 2, axis=1)

**Comment by axtimhaus** [comment]
Maybe just use `len(df["contour_lines"])`
