### ISSUE TITLE
Versionsinkompatibilität von einigen Modulen

### ISSUE THREAD

**Issue by Vuizur** [pyroll-project/pyroll-core#27]
Hallo zusammen,

ich hatte versucht, die neueste Betaversion von Pyroll von Pypi zu installieren, weil ich gesehen hatte, dass ihr den Reporter geupdated hattet und ich die neueste Betaversion verwenden möchte, damit ich den Code nicht später anpassen muss. 

Allerdings geht das momentan noch nicht, da die Versionen noch nicht ganz kompatibel sind:
pyroll-zouhar-contact hängt noch von pyroll ^1.0.0 ab, was dann eine Fehlermeldung verursacht.

(Am Rande würde ich vorschlagen, die Standard-Poetry-Versionslimits (bis zur nächsten Hauptversion der dependencies, markiert mit ^) durch offene Limits >= zu ersetzen, sofern keine Inkompatibilität der betroffenen Bibliothek bekannt ist (die pyroll-Sachen vielleicht ausgenommen, wenn die synchron sein sollen.). Das ist soweit ich weiß die Schlussfolgerung von Leuten, die darüber [zu viel nachgedacht haben](https://iscinumpy.dev/post/bound-version-constraints/), und ich hatte schon einmal in einem anderen Projekt durch Version Capping nervige Probleme. 😀)

Anderes Problem:
pyroll-zouhar-contact hat auch noch den 3.11 Version-Constraint, genauso wie pyroll-basic (Ich glaube, 3.11 wär für die GUI schon ziemlich cool, weil die Performance besser sein soll.)

**Comment by ChRen95** [comment]
Hallo Hannes, 
Ich geh morgen mal alle Pakete durch. 
Einige hängen noch auf alten Versionen weil es einfach nicht angepasst wurde.
Unser Problem mit Python 3.11 kommt aus numpy. Wir brauchen das an vielen Stellen und noch ist numpy nicht vollständig mit Python 3.11 kompatibel. Ich belese mich zu dem Thema heute nochmal und geb Rückmeldung. 
Zum Vorschlag mit den offnen Limits bin ich dafür und würde das auch so übernehmen.

**Comment by Vuizur** [comment]
Super, danke dir!

**Comment by ChRen95** [comment]
Also ich habe pyroll-zouar-contact erstmal hochgesetzt. 
Ich hoffe das jetzt erstmal alles läuft bei dir. Da Max und ich zeitnah sowieso jedes Paket auf Version 2.0 updaten würde ich die offenen Limits in poetry im gleichen Zug mitmachen.
