### ISSUE TITLE
Unit Class Hierarchy Concept

### ISSUE THREAD

**Issue by axtimhaus** [pyroll-project/pyroll-core#41]
I have created a chart visualizing the current class hierarchy of the unit classes.

I call for discussion regarding its logic and possible additions or changes.
I excluded the `DeformationUnit` from the chart, as it's just a common base for `RollPass` and `RollPass.DiskElement`. Including the `*.DiskELement` classes into the chart would end in a mess.

My personal concerns so far:
- maybe derive also `RollPass` from `Transport`, since atmosphere contact is also present 
- the current `Transport` derivatives are only rough concepts by now

![unit_hierarchy.png](https://user-images.githubusercontent.com/25556047/215725214-972700ee-6dd2-4004-8b3b-6946fd49e585.png)

**Comment by ChRen95** [comment]
Should be implemented in version 2.x. 
@mscImf  could you provide a list of reasonable base hooks for the shown units?

**Comment by mscImf** [comment]
Transport has also particular metallic contact to adjustage

Transport has maybe separate zone for gradually changes in heat transfer coefficients and radiation close to the roll gap (Wehage)

**Comment by mscImf** [comment]
>

**Comment by mscImf** [comment]
Transport needs reversal rolling (transport with virtual distance of length of slab and reversal data storage) or similar to rotator a reversal unit

Descaler needs hook for pressure dependent heat transfer coefficient.

Oxide scale development is needed for rolling and transport. (thickness, fracture, consistence --> Layers, thermodynamic...)

induction needs hook for volume heat source in thermal computation --> electromagnetic source

cooling needs material hook for phase transformation (FastLoRoll- TTT, CCT, DCCT, CCP) + hook for contribution of phase changes during cooling to thermal heat capacity, density and latent heat source in a thermal equation (lectures Modelling I)

transport needs material hook for phase transformation (FastLoRoll- TTT, CCT, DCCT, CCP)  + hook for contribution of phase changes during cooling to thermal heat capacity, density and latent heat source in a thermal equation (lectures Modelling I)

furnace needs hook for austenitization (TTA)

4 roll pass is needed similar to 3 roll pass (flat and profiled)

**Comment by ChRen95** [comment]
Would opt for closing this issue for now. I'm fine with the concept and would also not want to derive Transport from RollPass since a Transport and a RollPass are both the most basic units for a Rolling Process so they should both be independent base classes. Further I would close this, since it's to broad of an issue.
